# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Execute script
      run: "curl -X POST --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -H \"Accept: application/vnd.github.v3+json\" https://api.github.com/repos/qontract/petstore/actions/workflows/maven.yml/dispatches -d '{\"ref\":\"master\"}'"
      env:
        SECRET: ${{ secrets.PETSTORE_ACCESS_TOKEN }}
    - name: Execute script
      run: "curl -X POST --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -H \"Accept: application/vnd.github.v3+json\" https://api.github.com/repos/qontract/petstore-website/actions/workflows/maven.yml/dispatches -d '{\"ref\":\"master\"}'"
      env:
        SECRET: ${{ secrets.PETSTORE_ACCESS_TOKEN }}
